apiVersion: v1
kind: Service
metadata:
  name: amc-rules-svc
  labels:
    app: amc-rules
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: amc-rules
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amc-rules
spec:
  selector:
    matchLabels:
      app: amc-rules
  replicas: 1
  template:
    metadata:
      labels:
        app: amc-rules
    spec:
      containers:
        - name: amc-rules
          image: amc-rules-api:0.1.0
          ports:
            - containerPort: 8080
